### ISSUE TITLE
Version .6 create store-type fails

### ISSUE THREAD

**Issue by jhowland1** [Keyfactor/kfutil#39]
(base) PS C:\Windows\system32> kfutil store-types create --name AKV
kfutil : panic: interface conversion: interface {} is nil, not bool
At line:1 char:1
+ kfutil store-types create --name AKV
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: interfac...s nil, not bool:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
goroutine 1 [running]:
kfutil/cmd.glob..func34(0x175e4c0?, {0x135ded8?, 0x2?, 0x2?})
	kfutil/cmd/storeTypes.go:202 +0x15cb
github.com/spf13/cobra.(*Command).execute(0x175e4c0, {0xc000096b00, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x175cae0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
kfutil/cmd.Execute()
	kfutil/cmd/root.go:83 +0x25
main.main()
	kfutil/main.go:22 +0x17

**Comment by jhowland1** [comment]
issue seems to be around the AKV store all others worked.

side not your store list is in accurate
has test data and some default data like IIS, or JKS  these are default in the platform
